-- ============================================================
-- Seed Data: 50 Additional World Destinations
-- ============================================================

INSERT INTO public.destinations (name, region, country, tagline, description, image_url, cost_level, safety_rating, return_potential, best_months, avg_daily_budget, ideal_stay_duration, highlights, vibes) VALUES

-- ─── EUROPE ───────────────────────────────────────────────

('Santorini, Greece', 'Europe', 'Greece',
 'White-washed cliffs above a sunken volcano',
 'Watch the most famous sunset on Earth from Oia as the caldera glows amber and gold. Wander through blue-domed churches perched on volcanic cliffs, swim in hot springs heated by the sleeping volcano below, and taste wine grown in volcanic ash.',
 'https://images.unsplash.com/photo-1613395877344-13d4a8e0d49e?w=800&q=80',
 4, 5, 4, 'May–Oct', '$200–350', '5–7 days',
 '{"Oia Sunset","Caldera Cruise","Red Beach","Wine Tasting in Volcanic Vineyards","Akrotiri Ruins"}',
 '{"Romance","Culture","Food"}'),

('Amalfi Coast, Italy', 'Europe', 'Italy',
 'Pastel villages clinging to Mediterranean cliffs',
 'Drive the winding coastal road between Positano and Ravello with the Tyrrhenian Sea sparkling below. Eat handmade limoncello pasta on a terrace overlooking the water, explore the medieval alleyways of Amalfi, and swim in hidden coves only reachable by boat.',
 'https://images.unsplash.com/photo-1534113414509-0eec2bfb493f?w=800&q=80',
 5, 5, 5, 'May–Sep', '$250–400', '5–7 days',
 '{"Path of the Gods Hike","Positano Beach","Ravello Gardens","Limoncello Tasting","Emerald Grotto"}',
 '{"Romance","Food","Culture","Nature"}'),

('Dubrovnik, Croatia', 'Europe', 'Croatia',
 'The pearl of the Adriatic',
 'Walk the ancient city walls that encircle terracotta rooftops tumbling toward sapphire waters. Kayak around the fortified harbor at sunset, island-hop to Lokrum''s botanical gardens, and sip Croatian wine in candlelit stone cellars that have poured for centuries.',
 'https://images.unsplash.com/photo-1742744807117-129ced86fd34?w=800&q=80',
 3, 5, 4, 'May–Sep', '$120–220', '4–6 days',
 '{"City Walls Walk","Lokrum Island","Cable Car Sunset","Wine Bars in Old Town","Kayaking the Coast"}',
 '{"Culture","Romance","Adventure"}'),

('Swiss Alps, Switzerland', 'Europe', 'Switzerland',
 'Cathedral peaks and chocolate-box villages',
 'Ride the Glacier Express through valleys so perfect they look painted. Hike to turquoise alpine lakes beneath the Matterhorn, paraglide over Interlaken, and warm up with fondue in a centuries-old chalet while snow falls silently outside.',
 'https://images.unsplash.com/photo-1530122037265-a5f1f91d3b99?w=800&q=80',
 5, 5, 5, 'Jun–Sep, Dec–Mar', '$300–500', '7–10 days',
 '{"Glacier Express","Matterhorn Views","Paragliding Interlaken","Jungfraujoch Top of Europe","Lake Blausee"}',
 '{"Adventure","Nature","Romance"}'),

('Lisbon, Portugal', 'Europe', 'Portugal',
 'Seven hills of fado, tiles, and golden light',
 'Ride the iconic yellow tram through cobblestoned neighborhoods draped in hand-painted azulejo tiles. Listen to fado music in a dimly lit Alfama tavern, eat custard tarts still warm from the oven at Belém, and watch the sun set over the Tagus from a miradouro.',
 'https://images.unsplash.com/photo-1585208798174-6cedd86e019a?w=800&q=80',
 2, 4, 5, 'Mar–Oct', '$100–180', '5–7 days',
 '{"Tram 28","Pastéis de Belém","Alfama Fado Night","Time Out Market","Sintra Day Trip"}',
 '{"Culture","Food","Romance"}'),

('Edinburgh, Scotland', 'Europe', 'United Kingdom',
 'A gothic fairytale carved from volcanic rock',
 'Climb Arthur''s Seat for sweeping views of this dramatic city split between medieval Old Town and Georgian New Town. Explore underground vaults haunted by centuries of history, taste single malts in candlelit whisky bars, and wander the Royal Mile as bagpipes echo off ancient stone.',
 'https://images.unsplash.com/photo-1506377585622-bedcbb027afc?w=800&q=80',
 3, 5, 4, 'May–Sep', '$150–250', '4–6 days',
 '{"Arthur''s Seat Hike","Edinburgh Castle","Whisky Tasting","Underground Vaults","Royal Mile"}',
 '{"Culture","Food","Adventure"}'),

('Barcelona, Spain', 'Europe', 'Spain',
 'Where Gaudí''s dreams meet Mediterranean soul',
 'Stand beneath the soaring columns of Sagrada Família as kaleidoscopic light pours through stained glass. Get lost in the Gothic Quarter''s medieval lanes, eat tapas at La Boqueria, watch sunset from Park Güell, and feel the city pulse at midnight on La Rambla.',
 'https://images.unsplash.com/photo-1583422409516-2895a77efded?w=800&q=80',
 3, 4, 5, 'Apr–Jun, Sep–Oct', '$130–220', '5–7 days',
 '{"Sagrada Família","Park Güell","La Boqueria Market","Gothic Quarter","Beach at Barceloneta"}',
 '{"Culture","Food","Romance","Adventure"}'),

('Reykjavik & Golden Circle, Iceland', 'Europe', 'Iceland',
 'Fire and ice at the edge of the Arctic',
 'Chase the northern lights across lava fields, soak in the milky blue waters of a geothermal lagoon, walk between tectonic plates at Þingvellir, and stand humbled before waterfalls so powerful the ground trembles beneath your feet.',
 'https://images.unsplash.com/photo-1504829857797-ddff29c27927?w=800&q=80',
 5, 5, 4, 'Sep–Mar (lights), Jun–Aug (midnight sun)', '$250–400', '7–10 days',
 '{"Northern Lights","Blue Lagoon","Golden Circle","Glacier Hiking","Whale Watching"}',
 '{"Adventure","Nature"}'),

('Cinque Terre, Italy', 'Europe', 'Italy',
 'Five rainbow villages above the Ligurian Sea',
 'Hike the cliffside trail connecting five candy-colored fishing villages, each more impossibly beautiful than the last. Eat pesto made with basil grown on the terraced hillsides, swim in crystal coves, and drink Sciacchetrà wine as boats bob in tiny harbors below.',
 'https://images.unsplash.com/photo-1516483638261-f4dbaf036963?w=800&q=80',
 3, 5, 4, 'Apr–Jun, Sep–Oct', '$150–250', '3–5 days',
 '{"Sentiero Azzurro Trail","Vernazza Harbor","Monterosso Beach","Pesto Making Class","Sunset from Manarola"}',
 '{"Romance","Nature","Food","Adventure"}'),

('Prague, Czech Republic', 'Europe', 'Czech Republic',
 'A thousand spires above the Vltava',
 'Cross the medieval Charles Bridge at dawn as mist rises from the river and statues emerge like ghosts. Explore the largest ancient castle complex in the world, drink pilsner in a Gothic cellar brewery, and watch the astronomical clock perform its 600-year-old show.',
 'https://images.unsplash.com/photo-1541849546-216549ae216d?w=800&q=80',
 2, 5, 4, 'Apr–Jun, Sep–Oct', '$80–150', '4–5 days',
 '{"Charles Bridge at Dawn","Prague Castle","Astronomical Clock","Beer Culture","Old Town Square"}',
 '{"Culture","Food","Romance"}'),

-- ─── CENTRAL & SOUTH AMERICA ─────────────────────────────

('Cusco & Machu Picchu, Peru', 'Central & South America', 'Peru',
 'Lost city of the Incas above the clouds',
 'Trek the ancient Inca Trail through cloud forest to arrive at the Sun Gate as Machu Picchu materializes from the mist below. Wander Cusco''s cobblestoned streets where Inca walls support colonial churches, and feast on ceviche at one of the world''s best food scenes.',
 'https://images.unsplash.com/photo-1568805746970-0bbae56ab18b?w=800&q=80',
 2, 4, 4, 'May–Sep', '$80–160', '7–10 days',
 '{"Machu Picchu","Inca Trail Trek","Sacred Valley","San Pedro Market","Rainbow Mountain"}',
 '{"Adventure","Culture","Food","Nature"}'),

('Costa Rica', 'Central & South America', 'Costa Rica',
 'Pura vida between two oceans',
 'Zip-line through cloud forests alive with quetzals and howler monkeys, surf warm Pacific breaks at sunset, soak in volcanic hot springs beneath Arenal, and wake to toucans calling from the canopy of your jungle lodge.',
 'https://images.unsplash.com/photo-1592409482913-c3094afdb249?w=800&q=80',
 3, 5, 5, 'Dec–Apr', '$120–220', '10–14 days',
 '{"Arenal Volcano Hot Springs","Monteverde Cloud Forest","Manuel Antonio Beach","Zip-lining","Wildlife Spotting"}',
 '{"Adventure","Nature","Romance"}'),

('Galápagos Islands, Ecuador', 'Central & South America', 'Ecuador',
 'Evolution''s living laboratory',
 'Snorkel alongside marine iguanas and sea lions who have never learned to fear humans. Watch giant tortoises lumber through misty highlands, stand inches from blue-footed boobies performing their mating dance, and feel the primal wonder Darwin felt when he first stepped ashore.',
 'https://images.unsplash.com/photo-1544979590-37e9b47eb705?w=800&q=80',
 5, 5, 3, 'Jun–Nov', '$300–500', '7–10 days',
 '{"Giant Tortoise Encounters","Snorkeling with Sea Lions","Blue-footed Boobies","Volcanic Landscapes","Darwin Research Station"}',
 '{"Adventure","Nature"}'),

('Patagonian Lake District, Argentina', 'Central & South America', 'Argentina',
 'Chocolate, lakes, and Andean wilderness',
 'Kayak across emerald lakes framed by snow-capped volcanoes, hike through ancient araucaria forests, taste artisan chocolate in the alpine village of Bariloche, and drive the Route of Seven Lakes — one of the most beautiful roads on Earth.',
 'https://images.unsplash.com/photo-1551632811-561732d1e306?w=800&q=80',
 3, 4, 4, 'Nov–Mar', '$100–200', '7–10 days',
 '{"Route of Seven Lakes","Bariloche Chocolate Trail","Nahuel Huapi Lake","Cerro Catedral","Villa La Angostura"}',
 '{"Nature","Adventure","Food","Romance"}'),

('Cartagena, Colombia', 'Central & South America', 'Colombia',
 'Colonial jewel on the Caribbean coast',
 'Wander through the walled old city where bougainvillea spills from wrought-iron balconies over cobblestoned plazas. Dance salsa in an open-air courtyard, eat ceviche at a rooftop restaurant overlooking the cathedral, and boat to the Rosario Islands for turquoise Caribbean water.',
 'https://images.unsplash.com/photo-1534035265253-afe22046ba98?w=800&q=80',
 2, 3, 4, 'Dec–Apr', '$70–140', '5–7 days',
 '{"Walled City Walk","Rosario Islands","Getsemaní Street Art","Rooftop Sunset Drinks","Bazurto Market"}',
 '{"Culture","Food","Romance","Adventure"}'),

('Oaxaca, Mexico', 'Central & South America', 'Mexico',
 'Mexico''s culinary and cultural soul',
 'Taste mole negro made from a recipe passed down through generations, watch artisans shape black clay pottery in village workshops, wander through markets overflowing with chapulines and mezcal, and visit the ancient Zapotec ruins of Monte Albán perched above the valley.',
 'https://images.unsplash.com/photo-1578390432942-d38a498a1db7?w=800&q=80',
 1, 4, 5, 'Oct–Dec', '$50–100', '7–10 days',
 '{"Monte Albán Ruins","Mezcal Distillery Tour","Oaxacan Cooking Class","Hierve el Agua","Day of the Dead Festival"}',
 '{"Culture","Food","Adventure"}'),

-- ─── MIDDLE EAST ──────────────────────────────────────────

('Petra & Wadi Rum, Jordan', 'Middle East', 'Jordan',
 'Rose-red city carved from desert stone',
 'Walk through the narrow Siq canyon as towering walls close in, then gasp as the Treasury reveals itself in a blaze of rose-colored stone. Sleep under a blanket of stars in a Bedouin camp in Wadi Rum, where Mars-red dunes stretch to the horizon in every direction.',
 'https://images.unsplash.com/photo-1579606032821-4e6161c81571?w=800&q=80',
 3, 4, 3, 'Mar–May, Sep–Nov', '$100–200', '5–7 days',
 '{"The Treasury at Petra","Wadi Rum Desert Camp","Dead Sea Float","Monastery Hike","Bedouin Dinner Under Stars"}',
 '{"Adventure","Culture","Nature"}'),

('Istanbul, Turkey', 'Middle East', 'Turkey',
 'Where continents collide in a symphony of minarets',
 'Stand beneath the Hagia Sophia''s golden dome — a space that has been church, mosque, and museum across 1,500 years. Cruise the Bosphorus at sunset between Europe and Asia, haggle in the Grand Bazaar''s 4,000 shops, and taste kebabs that have been perfected over centuries.',
 'https://images.unsplash.com/photo-1541432901042-2d8bd64b4a9b?w=800&q=80',
 2, 4, 5, 'Apr–Jun, Sep–Nov', '$80–160', '5–7 days',
 '{"Hagia Sophia","Bosphorus Cruise","Grand Bazaar","Blue Mosque","Turkish Breakfast Feast"}',
 '{"Culture","Food","Romance"}'),

('Oman', 'Middle East', 'Oman',
 'Arabia''s hidden gem of fjords, forts, and dunes',
 'Drive through the dramatic Hajar Mountains to Jebel Shams — the Grand Canyon of Arabia. Camp in the Empty Quarter''s towering dunes, swim in turquoise wadis hidden in desert canyons, and explore ancient frankincense trading ports where the air still smells of resin.',
 'https://images.unsplash.com/photo-1597475681177-809cfdc76cd2?w=800&q=80',
 3, 5, 3, 'Oct–Apr', '$120–250', '7–10 days',
 '{"Wadi Shab Swimming","Jebel Shams Canyon","Wahiba Sands Desert Camp","Muscat Old Souk","Musandam Fjords"}',
 '{"Adventure","Nature","Culture"}'),

-- ─── ASIA ─────────────────────────────────────────────────

('Hanoi & Ha Long Bay, Vietnam', 'Asia Pacific', 'Vietnam',
 'Emerald karsts rising from silken waters',
 'Cruise past 1,600 limestone islands draped in jungle mist in Ha Long Bay. Wake at dawn in Hanoi''s Old Quarter to join tai chi by the lake, slurp the world''s best pho at a tiny street stall, and ride a motorbike through rice paddies in the northern highlands.',
 'https://images.unsplash.com/photo-1528127269322-539801943592?w=800&q=80',
 1, 4, 5, 'Oct–Apr', '$40–80', '10–14 days',
 '{"Ha Long Bay Cruise","Old Quarter Street Food","Ninh Binh Boat Ride","Sapa Rice Terraces","Water Puppet Show"}',
 '{"Culture","Food","Adventure","Nature"}'),

('Luang Prabang, Laos', 'Asia Pacific', 'Laos',
 'Monks, waterfalls, and Mekong serenity',
 'Rise before dawn to watch hundreds of saffron-robed monks silently collecting alms along the misty main street. Swim in the turquoise pools of Kuang Si waterfall, cruise the Mekong to mysterious cave temples, and eat sticky rice with your hands at the night market.',
 'https://images.unsplash.com/photo-1583417319070-4a69db38a482?w=800&q=80',
 1, 5, 4, 'Nov–Mar', '$30–60', '4–6 days',
 '{"Alms Giving Ceremony","Kuang Si Waterfalls","Mekong River Cruise","Night Market","Pak Ou Caves"}',
 '{"Culture","Nature","Food"}'),

('Rajasthan, India', 'Asia Pacific', 'India',
 'Land of maharajas, tiger reserves, and living color',
 'Sleep in a 500-year-old palace turned hotel, ride a camel across the Thar Desert at sunset, search for wild tigers in Ranthambore, and lose yourself in the electric blue streets of Jodhpur or the pink-walled bazaars of Jaipur.',
 'https://images.unsplash.com/photo-1599661046289-e31897846e41?w=800&q=80',
 2, 3, 4, 'Oct–Mar', '$60–150', '14–21 days',
 '{"Taj Mahal at Sunrise","Jaipur''s Amber Fort","Jodhpur Blue City","Thar Desert Camel Safari","Tiger Safari at Ranthambore"}',
 '{"Culture","Adventure","Food"}'),

('Sri Lanka', 'Asia Pacific', 'Sri Lanka',
 'Teardrop island of temples, tea, and wildlife',
 'Ride the famous blue train through emerald tea plantations draped in mist, climb the ancient rock fortress of Sigiriya, watch elephants gather at Minneriya, and surf warm Indian Ocean waves as the sun sets behind a palm-fringed beach.',
 'https://images.unsplash.com/photo-1586041828039-b8d193d6d1dc?w=800&q=80',
 1, 4, 4, 'Dec–Mar, Jul–Aug', '$40–90', '14–21 days',
 '{"Sigiriya Rock Fortress","Train to Ella","Yala Safari","Galle Fort","Tea Plantation Stay"}',
 '{"Adventure","Culture","Nature","Food"}'),

('Siem Reap, Cambodia', 'Asia Pacific', 'Cambodia',
 'Ancient temples swallowed by jungle',
 'Watch the sun rise over Angkor Wat — the largest religious monument ever built — as its five towers are mirrored in the reflecting pool. Explore temples strangled by the roots of giant fig trees, float through flooded forests on Tonle Sap, and eat amok curry in the lively pub street.',
 'https://images.unsplash.com/photo-1508159452718-d22b3b0fc5b5?w=800&q=80',
 1, 4, 4, 'Nov–Mar', '$30–70', '4–6 days',
 '{"Angkor Wat Sunrise","Ta Prohm Temple","Tonle Sap Lake","Phare Circus","Khmer Cooking Class"}',
 '{"Culture","Adventure","Food"}'),

('Seoul, South Korea', 'Asia Pacific', 'South Korea',
 'Ancient palaces meet neon-lit futurescape',
 'Wander through 600-year-old Joseon palaces, then step into a neon-drenched street food alley serving the crispiest Korean fried chicken on Earth. Hike fortress walls above the city, sing your heart out in a noraebang, and experience the K-beauty and K-BBQ culture firsthand.',
 'https://images.unsplash.com/photo-1534274988757-a28bf1a57c17?w=800&q=80',
 2, 5, 5, 'Mar–May, Sep–Nov', '$100–180', '5–7 days',
 '{"Gyeongbokgung Palace","Bukchon Hanok Village","Gwangjang Market","DMZ Tour","Namsan Tower Sunset"}',
 '{"Culture","Food","Adventure"}'),

('Taipei, Taiwan', 'Asia Pacific', 'Taiwan',
 'Night markets, hot springs, and mountain trails',
 'Eat your way through the sensory overload of Shilin Night Market, soak in natural hot springs in Beitou, hike through misty Yangmingshan National Park, and ride the gondola to a mountainside temple as the city glitters below.',
 'https://images.unsplash.com/photo-1470004914212-05527e49370b?w=800&q=80',
 2, 5, 5, 'Oct–Apr', '$60–120', '5–7 days',
 '{"Shilin Night Market","Jiufen Old Street","Beitou Hot Springs","Elephant Mountain Sunset","Taroko Gorge"}',
 '{"Food","Culture","Nature","Adventure"}'),

-- ─── PACIFIC & OCEANIA ────────────────────────────────────

('Fiji', 'Pacific', 'Fiji',
 'Where happiness is a warm turquoise lagoon',
 'Island-hop between palm-fringed atolls in the Yasawa chain, snorkel coral gardens teeming with tropical fish, drink kava in a village ceremony, and fall asleep in an overwater bure to the sound of gentle waves lapping beneath you.',
 'https://images.unsplash.com/photo-1551918120-9739cb430c6d?w=800&q=80',
 3, 5, 4, 'May–Oct', '$150–300', '7–10 days',
 '{"Yasawa Island Hopping","Kava Ceremony","Snorkeling the Reef","Beach Picnic on a Private Island","Fijian Lovo Feast"}',
 '{"Romance","Nature","Adventure","Culture"}'),

('Tasmania, Australia', 'Pacific', 'Australia',
 'Wild island at the edge of the world',
 'Hike the Overland Track through primordial wilderness, taste some of the world''s freshest oysters straight from the water, drive the east coast past deserted white sand beaches, and meet Tasmanian devils at a wildlife sanctuary.',
 'https://images.unsplash.com/photo-1516552065-3be0e8f2560d?w=800&q=80',
 3, 5, 4, 'Dec–Mar', '$150–250', '10–14 days',
 '{"Overland Track","Cradle Mountain","Freycinet & Wineglass Bay","MONA Museum","Bruny Island Oysters"}',
 '{"Nature","Adventure","Food"}'),

-- ─── AFRICA (additional) ─────────────────────────────────

('Victoria Falls, Zambia/Zimbabwe', 'Africa', 'Zambia',
 'The smoke that thunders',
 'Feel the earth shake as the world''s largest curtain of falling water crashes into the Batoka Gorge, sending spray 300 meters skyward. Raft the Zambezi''s legendary white water, bungee jump from the bridge between two nations, and watch elephants drink at sunset from your lodge.',
 'https://images.unsplash.com/photo-1534353473418-4cfa6c56fd38?w=800&q=80',
 3, 4, 3, 'Jun–Aug (falls peak), Sep–Dec (rafting)', '$150–300', '4–6 days',
 '{"Victoria Falls Walk","Zambezi White Water Rafting","Bridge Bungee Jump","Sunset Cruise","Chobe Day Trip"}',
 '{"Adventure","Nature"}'),

('Madagascar', 'Africa', 'Madagascar',
 'The eighth continent of lemurs and baobabs',
 'Walk through the otherworldly Avenue of the Baobabs at sunset, lock eyes with a ring-tailed lemur in a spiny forest found nowhere else on Earth, snorkel pristine reefs off Nosy Be, and navigate the dramatic tsingy limestone needles of Ankarana.',
 'https://images.unsplash.com/photo-1580746738099-78d6833b3e07?w=800&q=80',
 2, 3, 3, 'Apr–Nov', '$60–130', '14–21 days',
 '{"Avenue of the Baobabs","Lemur Encounters","Tsingy de Bemaraha","Nosy Be Beaches","Ranomafana Rainforest"}',
 '{"Adventure","Nature","Culture"}'),

('Zanzibar, Tanzania', 'Africa', 'Tanzania',
 'Spice island where Africa meets Arabia',
 'Wander Stone Town''s labyrinthine alleys past intricately carved wooden doors, taste cloves and nutmeg on a spice farm tour, swim in the impossibly turquoise waters of Nungwi Beach, and eat seafood at the Forodhani night market as dhows sail past.',
 'https://images.unsplash.com/photo-1580746738099-78d6833b3e07?w=800&q=80',
 2, 4, 4, 'Jun–Oct', '$70–150', '5–7 days',
 '{"Stone Town Walking Tour","Spice Farm Visit","Nungwi Beach","Forodhani Night Market","Jozani Forest Monkeys"}',
 '{"Culture","Food","Romance","Nature"}'),

('Namibia', 'Africa', 'Namibia',
 'Vast dunes, skeleton coasts, and star-drenched skies',
 'Climb the towering red dunes of Sossusvlei as the sun turns them to fire, drive the eerie Skeleton Coast past shipwrecks half-buried in sand, track desert-adapted elephants in Damaraland, and sleep under the clearest, most star-filled sky you''ve ever seen.',
 'https://images.unsplash.com/photo-1547471080-7cc2caa01a7e?w=800&q=80',
 3, 4, 3, 'May–Oct', '$120–250', '10–14 days',
 '{"Sossusvlei Dunes","Deadvlei","Skeleton Coast","Etosha Safari","Stargazing in NamibRand"}',
 '{"Adventure","Nature"}'),

('Rwanda', 'Africa', 'Rwanda',
 'Land of a thousand hills and mountain gorillas',
 'Trek through bamboo forest on the slopes of a volcano to sit face-to-face with a silverback mountain gorilla — one of only 1,000 left on Earth. Explore Kigali''s remarkable renewal, canoe on Lake Kivu, and hike through some of the most beautiful highlands in Africa.',
 'https://images.unsplash.com/photo-1580060839134-75a5edca2e99?w=800&q=80',
 4, 4, 3, 'Jun–Sep', '$200–400', '5–7 days',
 '{"Mountain Gorilla Trek","Kigali Genocide Memorial","Lake Kivu","Nyungwe Canopy Walk","Golden Monkey Tracking"}',
 '{"Adventure","Nature","Culture"}'),

-- ─── CARIBBEAN ────────────────────────────────────────────

('Cuba', 'Caribbean', 'Cuba',
 'Time-capsule island of rum, rhythm, and revolution',
 'Ride in a pastel 1950s convertible through Old Havana''s crumbling grandeur, listen to live son music spill from every doorway, sip mojitos where Hemingway drank, roll cigars with masters in Viñales, and swim in the untouched coral reefs of Jardines de la Reina.',
 'https://images.unsplash.com/photo-1500759285222-a95626b934cb?w=800&q=80',
 1, 4, 4, 'Nov–Apr', '$50–120', '7–10 days',
 '{"Old Havana Walking Tour","Classic Car Ride","Viñales Valley","Live Salsa Music","Trinidad Colonial Town"}',
 '{"Culture","Food","Adventure","Romance"}'),

('St. Lucia', 'Caribbean', 'St. Lucia',
 'Twin volcanic peaks above a tropical paradise',
 'Wake up to the iconic Pitons framed by your window, mud-bathe in a drive-in volcano, sail down the coast past banana plantations and fishing villages, and snorkel the Anse Chastanet reef where parrotfish glow like living jewels.',
 'https://images.unsplash.com/photo-1572726729207-a78d6feb18d7?w=800&q=80',
 4, 4, 4, 'Dec–May', '$200–350', '5–7 days',
 '{"The Pitons Hike","Sulphur Springs Volcano","Anse Chastanet Snorkeling","Catamaran Cruise","Chocolate & Cocoa Tour"}',
 '{"Romance","Nature","Adventure"}'),

-- ─── NORTH AMERICA ────────────────────────────────────────

('Banff & Canadian Rockies, Canada', 'North America', 'Canada',
 'Turquoise lakes cradled by cathedral peaks',
 'Canoe across the impossibly turquoise waters of Lake Louise, hike to hidden alpine meadows bursting with wildflowers, drive the Icefields Parkway — the most scenic road in North America — and soak in natural hot springs as elk graze nearby.',
 'https://images.unsplash.com/photo-1503614472-8c93d56e92ce?w=800&q=80',
 4, 5, 5, 'Jun–Sep, Dec–Mar', '$200–350', '7–10 days',
 '{"Lake Louise Canoeing","Icefields Parkway Drive","Moraine Lake","Banff Hot Springs","Johnston Canyon Hike"}',
 '{"Nature","Adventure","Romance"}'),

('Hawaii (Big Island)', 'North America', 'United States',
 'Where fire meets the Pacific',
 'Watch molten lava flow into the sea at Hawai''i Volcanoes National Park, snorkel with manta rays after dark, stargaze from the summit of Mauna Kea, and drive through 11 of the world''s 13 climate zones on a single island.',
 'https://images.unsplash.com/photo-1542259009477-d625272157b7?w=800&q=80',
 4, 5, 5, 'Apr–May, Sep–Nov', '$200–350', '7–10 days',
 '{"Hawai''i Volcanoes NP","Manta Ray Night Snorkel","Mauna Kea Stargazing","Waipi''o Valley","Black Sand Beach"}',
 '{"Adventure","Nature","Romance"}'),

('Utah''s Mighty Five, USA', 'North America', 'United States',
 'Red rock cathedrals carved by time',
 'Hike The Narrows through a slot canyon with the Virgin River flowing at your feet, watch the sun paint Delicate Arch amber at golden hour, mountain bike the slickrock trails of Moab, and camp under the Milky Way in some of the darkest skies in America.',
 'https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?w=800&q=80',
 3, 5, 4, 'Mar–May, Sep–Nov', '$120–220', '10–14 days',
 '{"Zion Narrows","Delicate Arch Sunset","Bryce Canyon Hoodoos","Canyonlands Mesa Arch","Capitol Reef Orchards"}',
 '{"Adventure","Nature"}'),

-- ─── SOUTHEAST ASIA (additional) ─────────────────────────

('Borneo, Malaysia', 'Asia Pacific', 'Malaysia',
 'Ancient rainforest where orangutans swing free',
 'Lock eyes with a wild orangutan in the canopy of 130-million-year-old rainforest, dive the legendary walls of Sipadan, trek to the summit of Mount Kinabalu at dawn, and cruise river channels where proboscis monkeys leap between trees.',
 'https://images.unsplash.com/photo-1590283603385-17ffb3a7f29f?w=800&q=80',
 2, 4, 4, 'Mar–Oct', '$60–140', '10–14 days',
 '{"Orangutan Encounters","Sipadan Diving","Mount Kinabalu","Kinabatangan River Safari","Danum Valley Rainforest"}',
 '{"Adventure","Nature"}'),

('Philippines (Palawan & Siargao)', 'Asia Pacific', 'Philippines',
 'Secret lagoons and endless island magic',
 'Kayak into the hidden lagoons of El Nido where limestone cliffs encircle emerald water, island-hop to deserted white sand beaches, surf the legendary Cloud 9 break in Siargao, and swim through the Underground River — one of the New 7 Wonders of Nature.',
 'https://images.unsplash.com/photo-1518509562904-e7ef99cdcc86?w=800&q=80',
 1, 4, 5, 'Dec–May', '$40–90', '10–14 days',
 '{"El Nido Island Hopping","Big Lagoon Kayaking","Cloud 9 Surfing","Underground River","Nacpan Beach"}',
 '{"Adventure","Nature","Romance"}'),

('Myanmar (Burma)', 'Asia Pacific', 'Myanmar',
 'Golden pagodas across an ancient landscape',
 'Float above 2,000 ancient temples in a hot air balloon as dawn breaks over the plains of Bagan. Watch fishermen balance on one leg on Inle Lake, cover a pagoda in gold leaf at Shwedagon, and trek through Shan State highlands to villages untouched by time.',
 'https://images.unsplash.com/photo-1540611025311-01df3cde54b5?w=800&q=80',
 1, 3, 3, 'Nov–Feb', '$30–70', '14–21 days',
 '{"Bagan Balloon Ride","Shwedagon Pagoda","Inle Lake","Mandalay Hill Sunset","Shan State Trekking"}',
 '{"Culture","Adventure","Nature"}'),

-- ─── EAST ASIA (additional) ──────────────────────────────

('Hokkaido, Japan', 'Asia Pacific', 'Japan',
 'Japan''s wild north of powder, ramen, and lavender',
 'Ski the legendary powder snow of Niseko, soak in an onsen while snow monkeys bathe nearby, eat the richest miso ramen in Japan in Sapporo, and drive through endless lavender fields in Furano that perfume the summer air.',
 'https://images.unsplash.com/photo-1551641506-ee5bf4cb45f1?w=800&q=80',
 3, 5, 5, 'Dec–Mar (ski), Jul–Aug (flowers)', '$150–280', '7–10 days',
 '{"Niseko Powder Skiing","Sapporo Ramen Alley","Furano Lavender Fields","Noboribetsu Onsen","Otaru Canal Walk"}',
 '{"Adventure","Food","Nature","Romance"}'),

('Zhangjiajie, China', 'Asia Pacific', 'China',
 'The floating mountains that inspired Avatar',
 'Walk on a glass bridge suspended between sandstone pillars that pierce the clouds — the landscape that inspired Pandora. Ride the world''s tallest outdoor elevator up a cliff face, hike through mist-shrouded forests, and explore the cave systems hidden within.',
 'https://images.unsplash.com/photo-1537531383496-f4749b02b2d5?w=800&q=80',
 2, 4, 3, 'Apr–Jun, Sep–Nov', '$60–120', '3–5 days',
 '{"Avatar Hallelujah Mountain","Zhangjiajie Glass Bridge","Bailong Elevator","Golden Whip Stream","Tianmen Mountain"}',
 '{"Adventure","Nature"}'),

-- ─── INDIAN OCEAN ─────────────────────────────────────────

('Maldives', 'Indian Ocean', 'Maldives',
 'Overwater paradise on a coral atoll',
 'Wake up in an overwater villa and step directly into bathwater-warm turquoise lagoon. Snorkel with whale sharks and manta rays, dine on a sandbank that disappears at high tide, and watch bioluminescent plankton turn the beach into a galaxy at your feet.',
 'https://images.unsplash.com/photo-1514282401047-d79a71a590e8?w=800&q=80',
 5, 5, 4, 'Nov–Apr', '$400–800', '5–7 days',
 '{"Overwater Villa Stay","Whale Shark Snorkeling","Sandbank Dining","Bioluminescent Beach","Manta Ray Night Dive"}',
 '{"Romance","Nature","Adventure"}'),

('Seychelles', 'Indian Ocean', 'Seychelles',
 'Granite boulders and untouched tropical perfection',
 'Swim between giant granite boulders on Anse Source d''Argent — the most photographed beach on Earth. Hike through the Vallée de Mai where coco de mer palms grow wild, spot giant tortoises on Curieuse Island, and kayak to deserted coves only accessible by sea.',
 'https://images.unsplash.com/photo-1589979481223-deb893043163?w=800&q=80',
 5, 5, 3, 'Apr–May, Oct–Nov', '$300–600', '7–10 days',
 '{"Anse Source d''Argent","Vallée de Mai","Giant Tortoise Encounters","Island Hopping","Creole Cuisine"}',
 '{"Romance","Nature","Adventure"}'),

('Mauritius', 'Indian Ocean', 'Mauritius',
 'Where the underwater waterfall meets paradise',
 'Fly over the surreal underwater waterfall illusion off Le Morne, hike through Black River Gorges to hidden waterfalls, taste rum at colonial-era distilleries, and swim with dolphins in the warm Indian Ocean as volcanic peaks tower behind you.',
 'https://images.unsplash.com/photo-1589979481223-deb893043163?w=800&q=80',
 3, 5, 4, 'May–Dec', '$150–300', '7–10 days',
 '{"Underwater Waterfall Helicopter Tour","Black River Gorges","Le Morne Hike","Chamarel Seven Colored Earths","Rum Distillery Tour"}',
 '{"Romance","Nature","Adventure","Food"}'),

-- ─── CENTRAL ASIA ─────────────────────────────────────────

('Uzbekistan', 'Central Asia', 'Uzbekistan',
 'Silk Road cities of turquoise and gold',
 'Stand in Samarkand''s Registan Square as three massive madrasas glow in turquoise tile under the Central Asian sun. Sleep in a caravanserai along the ancient Silk Road, haggle in Bukhara''s covered bazaars, and eat plov — the king of Uzbek cuisine — cooked in a cauldron for a thousand guests.',
 'https://images.unsplash.com/photo-1596484552834-6a58f850e0a1?w=800&q=80',
 1, 4, 3, 'Apr–Jun, Sep–Oct', '$30–70', '10–14 days',
 '{"Registan Square","Bukhara Old City","Shah-i-Zinda Necropolis","Khiva Walled City","Plov Center Tashkent"}',
 '{"Culture","Food","Adventure"}'),

-- ─── ADDITIONAL EUROPE ────────────────────────────────────

('Norwegian Fjords, Norway', 'Europe', 'Norway',
 'Vertical waterfalls plunging into mirror-still fjords',
 'Cruise through Geirangerfjord as waterfalls cascade from cliffs a thousand meters above. Hike to Trolltunga — a tongue of rock jutting over a 700-meter drop — kayak through narrow fjords at midnight under the summer sun, and spot orcas in the Arctic waters of Tromsø.',
 'https://images.unsplash.com/photo-1513519245088-0e12902e5a38?w=800&q=80',
 5, 5, 4, 'Jun–Aug (fjords), Nov–Mar (northern lights)', '$250–400', '10–14 days',
 '{"Geirangerfjord Cruise","Trolltunga Hike","Fjord Kayaking","Northern Lights in Tromsø","Bergen''s Bryggen Wharf"}',
 '{"Adventure","Nature","Romance"}'),

('Provence, France', 'Europe', 'France',
 'Lavender fields and rosé-tinted afternoons',
 'Drive through rolling lavender fields that stretch to the horizon in purple waves, browse village markets overflowing with olives and cheese, explore Roman ruins in Arles, taste wine in centuries-old cellars in Châteauneuf-du-Pape, and cook with a French grandmother in her farmhouse kitchen.',
 'https://images.unsplash.com/photo-1498747946579-bde899e3f7f0?w=800&q=80',
 4, 5, 5, 'Jun–Sep', '$180–300', '7–10 days',
 '{"Lavender Fields of Valensole","Gordes Village","Pont du Gard","Wine Tasting in Châteauneuf","Provençal Cooking Class"}',
 '{"Romance","Food","Culture","Nature"}'),

('Dolomites, Italy', 'Europe', 'Italy',
 'Jagged pink peaks above alpine meadows',
 'Hike the Alta Via trail beneath the jagged spires of Tre Cime di Lavaredo glowing pink at sunset. Stay in a mountain rifugio with views that steal your breath, cycle legendary Tour de France passes, and eat hearty South Tyrolean cuisine where Italian and Austrian flavors collide.',
 'https://images.unsplash.com/photo-1556449895-a33c9dba33dd?w=800&q=80',
 3, 5, 4, 'Jun–Sep, Dec–Mar', '$150–280', '7–10 days',
 '{"Tre Cime di Lavaredo","Seceda Ridgeline","Lago di Braies","Alta Via Hike","Rifugio Stay"}',
 '{"Adventure","Nature","Food","Romance"}');
